services:
  - type: web
    name: ai-psm-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://ai-psm-backend.onrender.com
      - key: VITE_ADMIN_URL
        value: https://ai-psm-admin.onrender.com
